# Generated by Django 5.0.6 on 2026-07-01 09:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name="Montant d'activation (bloqué)"),
        ),
        migrations.AddField(
            model_name='user',
            name='commission_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Cumul des commissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_activated',
            field=models.BooleanField(default=False, verbose_name='Compte activé'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_withdrawal_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date du dernier retrait'),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_commissions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Commissions en attente'),
        ),
        migrations.AddField(
            model_name='user',
            name='withdrawal_requested',
            field=models.BooleanField(default=False, verbose_name='Retrait en attente de validation'),
        ),
        migrations.AddField(
            model_name='user',
            name='withdrawal_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de la demande de retrait'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('APPRENTI', 'Apprenti'), ('COMPAGNON_N3', 'Compagnon Niveau 3'), ('COMPAGNON_N2', 'Compagnon Niveau 2'), ('COMPAGNON_N1', 'Compagnon Niveau 1'), ('MAITRE_N3', 'Maître Niveau 3'), ('MAITRE_N2', 'Maître Niveau 2'), ('MAITRE_N1', 'Maître Niveau 1'), ('GRAND_MAITRE', 'Grand Maître')], default='APPRENTI', max_length=20, verbose_name='Grade'),
        ),
    ]
