# Generated by Django 5.0.6 on 2026-07-17 12:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_activation_amount_user_commission_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name="Solde d'activation (bloqué à vie)"),
        ),
        migrations.AlterField(
            model_name='user',
            name='commission_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, verbose_name='Solde des commissions'),
        ),
    ]
