# Generated by Django 5.0.6 on 2026-06-25 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NiveauReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom du niveau')),
                ('niveau', models.IntegerField(unique=True, verbose_name='Ordre du niveau')),
                ('pourcentage_commission', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pourcentage de commission (%)')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Niveau de referral',
                'verbose_name_plural': 'Niveaux de referral',
                'ordering': ['niveau'],
            },
        ),
        migrations.CreateModel(
            name='Loge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la loge')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_active', models.BooleanField(default=True)),
                ('grand_maitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loges_dirigees', to=settings.AUTH_USER_MODEL, verbose_name='Grand Maître')),
            ],
            options={
                'verbose_name': 'Loge',
                'verbose_name_plural': 'Loges',
            },
        ),
        migrations.CreateModel(
            name='RelationParrainage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_parrainage', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('filleul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parrainages_recus', to=settings.AUTH_USER_MODEL, verbose_name='Filleul')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referrals.niveaureferral', verbose_name='Niveau de relation')),
                ('parrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parrainages_donnes', to=settings.AUTH_USER_MODEL, verbose_name='Parrain')),
            ],
            options={
                'verbose_name': 'Relation de parrainage',
                'verbose_name_plural': 'Relations de parrainage',
                'unique_together': {('parrain', 'filleul')},
            },
        ),
    ]
