# Generated by Django 5.0.6 on 2026-06-25 10:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('DEPOT', 'Dépôt'), ('RETRAIT', 'Retrait'), ('COMMISSION', 'Commission'), ('BONUS', 'Bonus')], max_length=20, verbose_name='Type')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('frais', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Frais (FCFA)')),
                ('montant_net', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant net (FCFA)')),
                ('moyen_paiement', models.CharField(blank=True, choices=[('WAVE', 'Wave CI'), ('MOOV', 'Moov Money'), ('MTN', 'MTN Mobile Money'), ('ORANGE', 'Orange Money')], max_length=20, null=True, verbose_name='Moyen de paiement')),
                ('reference_paiement', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence paiement externe')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('niveau_commission', models.IntegerField(blank=True, null=True, verbose_name='Niveau de commission')),
                ('transaction_originale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='transactions.transaction', verbose_name='Transaction originale')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date_transaction'],
            },
        ),
        migrations.CreateModel(
            name='DistributionCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (FCFA)')),
                ('pourcentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pourcentage (%)')),
                ('niveau', models.IntegerField(verbose_name='Niveau de distribution')),
                ('date_distribution', models.DateTimeField(auto_now_add=True)),
                ('est_paye', models.BooleanField(default=False)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions_recues', to=settings.AUTH_USER_MODEL, verbose_name='Bénéficiaire')),
                ('transaction_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='transactions.transaction', verbose_name='Transaction source')),
            ],
            options={
                'verbose_name': 'Distribution de commission',
                'verbose_name_plural': 'Distributions de commission',
            },
        ),
    ]
